import { createFlagDesign, type FlagGenerationOptions } from "./flagGenerator";
import type { FlagPreset } from "./flagTypes";

function preset(id: string, name: string, description: string, options: FlagGenerationOptions): FlagPreset {
  return {
    id,
    name,
    description,
    design: createFlagDesign(options),
  };
}

export const FLAG_PRESETS: FlagPreset[] = [
  preset("aurora-vanguard", "Aurora Vanguard", "A crisp command emblem with a formal geometric field and a bright forward-facing symbol.", {
    seed: "aurora-vanguard",
    containerId: "shield",
    colorId: "midnight",
    accentColorId: "azure",
    patternId: "radial-sunburst",
    primarySymbolId: "starburst",
    secondarySymbolId: "halo-anchor",
  }),
  preset("solar-citadel", "Solar Citadel", "A ceremonial emblem built around a core solar mark with a strong protective frame.", {
    seed: "solar-citadel",
    containerId: "octagon",
    colorId: "ivory",
    accentColorId: "gold",
    patternId: "concentric-rings",
    primarySymbolId: "solar-disk",
    secondarySymbolId: "crest-chevron",
  }),
  preset("crimson-helix", "Crimson Helix", "A sharp aggressive mark with diagonal motion and a dense high-contrast field.", {
    seed: "crimson-helix",
    containerId: "hexagon",
    colorId: "crimson",
    accentColorId: "ivory",
    patternId: "diagonal-band",
    primarySymbolId: "circuit-knot",
    secondarySymbolId: "blade-pair",
  }),
  preset("jade-orbit", "Jade Orbit", "A balanced orbital emblem with calm geometry and a compact ceremonial core.", {
    seed: "jade-orbit",
    containerId: "circle",
    colorId: "jade",
    accentColorId: "silver",
    patternId: "concentric-rings",
    primarySymbolId: "ring-node",
    secondarySymbolId: "loop-knot",
  }),
  preset("midnight-bastion", "Midnight Bastion", "A defensive seal with a dark field, sharp edge language, and a shield-like silhouette.", {
    seed: "midnight-bastion",
    containerId: "shield",
    colorId: "obsidian",
    accentColorId: "silver",
    patternId: "split-horizontal",
    primarySymbolId: "beacon-crown",
    secondarySymbolId: "arch-gate",
  }),
  preset("ember-lattice", "Ember Lattice", "A warm industrial emblem with layered geometry and a disciplined central lattice.", {
    seed: "ember-lattice",
    containerId: "square",
    colorId: "amber",
    accentColorId: "copper",
    patternId: "dot-grid",
    primarySymbolId: "lattice-bloom",
    secondarySymbolId: "hex-core",
  }),
  preset("ocean-ward", "Ocean Ward", "A cool maritime-style emblem with a clean split field and a controlled crest.", {
    seed: "ocean-ward",
    containerId: "octagon",
    colorId: "teal",
    accentColorId: "white",
    patternId: "split-vertical",
    primarySymbolId: "wave-stack",
    secondarySymbolId: "eye-lens",
  }),
  preset("north-star", "North Star", "A bright navigational symbol with a crisp central point and a clean formal outline.", {
    seed: "north-star",
    containerId: "circle",
    colorId: "slate",
    accentColorId: "ivory",
    patternId: "none",
    primarySymbolId: "starburst",
    secondarySymbolId: "ring-node",
  }),
  preset("verdant-halo", "Verdant Halo", "A living-world emblem with rounded geometry and a soft orbital rhythm.", {
    seed: "verdant-halo",
    containerId: "hexagon",
    colorId: "emerald",
    accentColorId: "sand",
    patternId: "corner-glow",
    primarySymbolId: "halo-anchor",
    secondarySymbolId: "plume-triad",
  }),
  preset("regal-prism", "Regal Prism", "A formal high-status emblem with a faceted center and a regal container shape.", {
    seed: "regal-prism",
    containerId: "shield",
    colorId: "plum",
    accentColorId: "gold",
    patternId: "radial-sunburst",
    primarySymbolId: "crown-prism",
    secondarySymbolId: "split-diamond",
  }),
  preset("iron-comet", "Iron Comet", "A hard-edged industrial emblem with motion lines and a compact strike silhouette.", {
    seed: "iron-comet",
    containerId: "square",
    colorId: "slate",
    accentColorId: "amber",
    patternId: "wave-lines",
    primarySymbolId: "blade-pair",
    secondarySymbolId: "crystal-shard",
  }),
  preset("tide-signal", "Tide Signal", "A fluid ceremonial emblem with soft contrast, nested bands, and a calm pulse.", {
    seed: "tide-signal",
    containerId: "circle",
    colorId: "azure",
    accentColorId: "ivory",
    patternId: "wave-lines",
    primarySymbolId: "wave-stack",
    secondarySymbolId: "solar-disk",
  }),
  preset("sunline-compact", "Sunline Compact", "A minimal emblem with strong order, tight structure, and a luminous top line.", {
    seed: "sunline-compact",
    containerId: "octagon",
    colorId: "sand",
    accentColorId: "gold",
    patternId: "split-horizontal",
    primarySymbolId: "arch-gate",
    secondarySymbolId: "beacon-crown",
  }),
  preset("vector-fort", "Vector Fort", "A disciplined geometric seal with a pronounced defensive profile.", {
    seed: "vector-fort",
    containerId: "shield",
    colorId: "indigo",
    accentColorId: "silver",
    patternId: "chevron-stack",
    primarySymbolId: "crest-chevron",
    secondarySymbolId: "hex-core",
  }),
  preset("ion-promise", "Ion Promise", "A bright energetic emblem with clean transitions and a precise core symbol.", {
    seed: "ion-promise",
    containerId: "hexagon",
    colorId: "cobalt",
    accentColorId: "white",
    patternId: "corner-glow",
    primarySymbolId: "eye-lens",
    secondarySymbolId: "ring-node",
  }),
  preset("copper-array", "Copper Array", "A warm technical emblem composed of stacked forms and a centered industrial mark.", {
    seed: "copper-array",
    containerId: "square",
    colorId: "copper",
    accentColorId: "sand",
    patternId: "dot-grid",
    primarySymbolId: "circuit-knot",
    secondarySymbolId: "lattice-bloom",
  }),
  preset("lunar-chain", "Lunar Chain", "A cold ceremonial symbol with interlocking geometry and restrained contrast.", {
    seed: "lunar-chain",
    containerId: "circle",
    colorId: "silver",
    accentColorId: "midnight",
    patternId: "concentric-rings",
    primarySymbolId: "loop-knot",
    secondarySymbolId: "split-diamond",
  }),
  preset("atlas-crest", "Atlas Crest", "A broad civic emblem with sturdy geometry and a prominent crown-like top.", {
    seed: "atlas-crest",
    containerId: "shield",
    colorId: "olive",
    accentColorId: "ivory",
    patternId: "none",
    primarySymbolId: "crown-prism",
    secondarySymbolId: "apex-wings",
  }),
  preset("storm-quartz", "Storm Quartz", "A sharp mineral emblem with fractured geometry and energetic accents.", {
    seed: "storm-quartz",
    containerId: "hexagon",
    colorId: "plum",
    accentColorId: "azure",
    patternId: "diagonal-band",
    primarySymbolId: "crystal-shard",
    secondarySymbolId: "split-diamond",
  }),
  preset("onyx-beacon", "Onyx Beacon", "A dark command emblem with a bright point of focus and a simple, authoritative profile.", {
    seed: "onyx-beacon",
    containerId: "octagon",
    colorId: "obsidian",
    accentColorId: "gold",
    patternId: "radial-sunburst",
    primarySymbolId: "beacon-crown",
    secondarySymbolId: "starburst",
  }),
  preset("auric-loom", "Auric Loom", "A ceremonial weave of gold and ivory lines with a delicate but readable structure.", {
    seed: "auric-loom",
    containerId: "circle",
    colorId: "gold",
    accentColorId: "ivory",
    patternId: "wave-lines",
    primarySymbolId: "lattice-bloom",
    secondarySymbolId: "halo-anchor",
  }),
  preset("reef-signal", "Reef Signal", "A coastal-style emblem with a layered flow and an unmistakable central lens.", {
    seed: "reef-signal",
    containerId: "square",
    colorId: "teal",
    accentColorId: "sand",
    patternId: "split-vertical",
    primarySymbolId: "eye-lens",
    secondarySymbolId: "wave-stack",
  }),
  preset("ember-nexus", "Ember Nexus", "A dense hot emblem with a core node and radiating industrial symmetry.", {
    seed: "ember-nexus",
    containerId: "hexagon",
    colorId: "maroon",
    accentColorId: "amber",
    patternId: "radial-sunburst",
    primarySymbolId: "hex-core",
    secondarySymbolId: "starburst",
  }),
  preset("glacier-order", "Glacier Order", "A crisp institutional emblem with calm blue-white contrast and a disciplined frame.", {
    seed: "glacier-order",
    containerId: "shield",
    colorId: "white",
    accentColorId: "cobalt",
    patternId: "split-horizontal",
    primarySymbolId: "arch-gate",
    secondarySymbolId: "plume-triad",
  }),
  preset("violet-pylon", "Violet Pylon", "A tall formal emblem with a ceremonial vertical emphasis and luminous edges.", {
    seed: "violet-pylon",
    containerId: "octagon",
    colorId: "plum",
    accentColorId: "silver",
    patternId: "chevron-stack",
    primarySymbolId: "twin-spires",
    secondarySymbolId: "beacon-crown",
  }),
  preset("naval-lattice", "Naval Lattice", "A clean command emblem with lattice structure and a maritime color balance.", {
    seed: "naval-lattice",
    containerId: "circle",
    colorId: "cobalt",
    accentColorId: "gold",
    patternId: "dot-grid",
    primarySymbolId: "lattice-bloom",
    secondarySymbolId: "ring-node",
  }),
  preset("dawn-keeper", "Dawn Keeper", "A light-forward emblem with a protective feel and a readable rising crest.", {
    seed: "dawn-keeper",
    containerId: "shield",
    colorId: "ivory",
    accentColorId: "crimson",
    patternId: "corner-glow",
    primarySymbolId: "crest-chevron",
    secondarySymbolId: "apex-wings",
  }),
  preset("ember-helix", "Ember Helix", "A tight, energetic emblem with rotating loop forms and warm metallic contrast.", {
    seed: "ember-helix",
    containerId: "hexagon",
    colorId: "amber",
    accentColorId: "maroon",
    patternId: "concentric-rings",
    primarySymbolId: "loop-knot",
    secondarySymbolId: "circuit-knot",
  }),
  preset("signal-dais", "Signal Dais", "A platform-like emblem with a ceremonial base and a raised central mark.", {
    seed: "signal-dais",
    containerId: "square",
    colorId: "slate",
    accentColorId: "gold",
    patternId: "none",
    primarySymbolId: "arch-gate",
    secondarySymbolId: "solar-disk",
  }),
  preset("vector-aegis", "Vector Aegis", "A compact defensive seal with a hard frame, a strong core, and clean vector geometry.", {
    seed: "vector-aegis",
    containerId: "shield",
    colorId: "midnight",
    accentColorId: "teal",
    patternId: "split-vertical",
    primarySymbolId: "blade-pair",
    secondarySymbolId: "halo-anchor",
  }),
  preset("golden-trace", "Golden Trace", "A luminous symbolic emblem with traced lines and a formal ceremonial layout.", {
    seed: "golden-trace",
    containerId: "octagon",
    colorId: "gold",
    accentColorId: "white",
    patternId: "wave-lines",
    primarySymbolId: "solar-disk",
    secondarySymbolId: "crown-prism",
  }),
];
