export type SpeciesId = string;

export type SpeciesArchetypeId = "humanoid" | "avian" | "reptilian" | "aquatic" | "fungoid";

export type SpeciesTraitId =
  | "adaptive"
  | "intelligent"
  | "rapidBreeders"
  | "industrious"
  | "agrarian"
  | "ingenious"
  | "communal"
  | "charismatic"
  | "conservationist"
  | "resilient"
  | "nonadaptive"
  | "slowBreeders"
  | "wasteful"
  | "unruly"
  | "delicate";

export type LivingStandardId = "luxurious" | "comfortable" | "basic" | "subsistence" | "oppressed";
export type CitizenshipStatusId = "fullCitizenship" | "residence" | "limitedRights" | "nonCitizen";
export type MigrationRightsId = "free" | "controlled" | "prohibited";
export type WorkEligibilityId = "allJobs" | "noAuthority" | "laborOnly";
export type SpeciesRightsCategory = "livingStandard" | "citizenship" | "migration" | "workEligibility";

export interface SpeciesArchetypeDefinition {
  id: SpeciesArchetypeId;
  name: string;
  icon: string;
  summary: string;
}

export interface SpeciesTraitDefinition {
  id: SpeciesTraitId;
  name: string;
  pointCost: number;
  polarity: "positive" | "negative";
  description: string;
}

export interface SpeciesState {
  id: SpeciesId;
  name: string;
  archetypeId: SpeciesArchetypeId;
  traitIds: SpeciesTraitId[];
  originFactionId?: number | null;
}

export interface SpeciesSetup {
  speciesName: string;
  archetypeId: SpeciesArchetypeId;
  traitIds: SpeciesTraitId[];
}

export interface SpeciesTraitValidation {
  valid: boolean;
  remainingPoints: number;
  errors: string[];
  normalizedTraitIds: SpeciesTraitId[];
}

export interface SpeciesRights {
  livingStandard: LivingStandardId;
  citizenship: CitizenshipStatusId;
  migration: MigrationRightsId;
  workEligibility: WorkEligibilityId;
}

export interface FactionSpeciesRightsState {
  factionId: number;
  rightsBySpeciesId: Record<SpeciesId, SpeciesRights>;
}

export interface SpeciesRightsOption<TId extends string = string> {
  id: TId;
  name: string;
  summary: string;
  description: string;
}

export interface SpeciesRightsOptionAvailability<TId extends string = string> extends SpeciesRightsOption<TId> {
  allowed: boolean;
  reason?: string;
}

export interface LegalSpeciesRightsOptions {
  livingStandards: Array<SpeciesRightsOptionAvailability<LivingStandardId>>;
  citizenship: Array<SpeciesRightsOptionAvailability<CitizenshipStatusId>>;
  migration: Array<SpeciesRightsOptionAvailability<MigrationRightsId>>;
  workEligibility: Array<SpeciesRightsOptionAvailability<WorkEligibilityId>>;
}

export interface SpeciesLawSelections {
  civilRights?: string;
  speciesPolicy?: string;
}

export interface SpeciesEconomyEffects {
  habitabilityAdd: number;
  growthMultiplier: number;
  housingUsageMultiplier: number;
  amenitiesMultiplier: number;
  goodsUpkeepMultiplier: number;
  happinessAdd: number;
  crimeAdd: number;
  stabilityAdd: number;
}

export const HUMAN_SPECIES_ID = "human";
export const SPECIES_TRAIT_POINT_BUDGET = 3;
export const SPECIES_TRAIT_MAX_COUNT = 5;

export const SPECIES_ARCHETYPES: SpeciesArchetypeDefinition[] = [
  { id: "humanoid", name: "Humanoid", icon: "HU", summary: "Balanced terrestrial societies." },
  { id: "avian", name: "Avian", icon: "AV", summary: "Light-boned aerial-descended species." },
  { id: "reptilian", name: "Reptilian", icon: "RP", summary: "Hardy cold-blooded lineages." },
  { id: "aquatic", name: "Aquatic", icon: "AQ", summary: "Oceanic or amphibious civilizations." },
  { id: "fungoid", name: "Fungoid", icon: "FG", summary: "Spore-linked communal organisms." },
];

export const SPECIES_TRAITS: SpeciesTraitDefinition[] = [
  { id: "adaptive", name: "Adaptive", pointCost: 2, polarity: "positive", description: "+10 habitability on every planet." },
  { id: "intelligent", name: "Intelligent", pointCost: 2, polarity: "positive", description: "+10% researcher research output." },
  { id: "rapidBreeders", name: "Rapid Breeders", pointCost: 2, polarity: "positive", description: "+10% population growth contribution." },
  { id: "industrious", name: "Industrious", pointCost: 1, polarity: "positive", description: "+10% miner mineral output." },
  { id: "agrarian", name: "Agrarian", pointCost: 1, polarity: "positive", description: "+10% farmer food output." },
  { id: "ingenious", name: "Ingenious", pointCost: 1, polarity: "positive", description: "+10% technician energy output." },
  { id: "communal", name: "Communal", pointCost: 1, polarity: "positive", description: "-10% housing usage." },
  { id: "charismatic", name: "Charismatic", pointCost: 1, polarity: "positive", description: "+10% amenities generated by jobs." },
  { id: "conservationist", name: "Conservationist", pointCost: 1, polarity: "positive", description: "-10% consumer goods upkeep." },
  { id: "resilient", name: "Resilient", pointCost: 1, polarity: "positive", description: "-5 crime pressure and +1 stability contribution." },
  { id: "nonadaptive", name: "Nonadaptive", pointCost: -1, polarity: "negative", description: "-10 habitability on every planet." },
  { id: "slowBreeders", name: "Slow Breeders", pointCost: -1, polarity: "negative", description: "-10% population growth contribution." },
  { id: "wasteful", name: "Wasteful", pointCost: -1, polarity: "negative", description: "+15% consumer goods upkeep." },
  { id: "unruly", name: "Unruly", pointCost: -1, polarity: "negative", description: "+5 crime pressure." },
  { id: "delicate", name: "Delicate", pointCost: -1, polarity: "negative", description: "-5% lower-class job output." },
];

export const SPECIES_ARCHETYPE_BY_ID: Record<SpeciesArchetypeId, SpeciesArchetypeDefinition> = Object.fromEntries(
  SPECIES_ARCHETYPES.map((archetype) => [archetype.id, archetype]),
) as Record<SpeciesArchetypeId, SpeciesArchetypeDefinition>;

export const SPECIES_TRAIT_BY_ID: Record<SpeciesTraitId, SpeciesTraitDefinition> = Object.fromEntries(
  SPECIES_TRAITS.map((trait) => [trait.id, trait]),
) as Record<SpeciesTraitId, SpeciesTraitDefinition>;

export const LIVING_STANDARD_OPTIONS: Array<SpeciesRightsOption<LivingStandardId>> = [
  { id: "luxurious", name: "Luxurious", summary: "High goods upkeep, high happiness.", description: "Extensive state-backed luxuries and comfort guarantees." },
  { id: "comfortable", name: "Comfortable", summary: "Moderate goods upkeep and happiness.", description: "Broad consumer access and stable civic support." },
  { id: "basic", name: "Basic", summary: "Baseline upkeep and happiness.", description: "Standard rationing and public services." },
  { id: "subsistence", name: "Subsistence", summary: "Low goods upkeep, lower happiness.", description: "Minimal support focused on survival and labor continuity." },
  { id: "oppressed", name: "Oppressed", summary: "Very low upkeep, severe unrest.", description: "Coercive deprivation that sharply damages social outcomes." },
];

export const CITIZENSHIP_OPTIONS: Array<SpeciesRightsOption<CitizenshipStatusId>> = [
  { id: "fullCitizenship", name: "Full Citizenship", summary: "Full civic participation.", description: "Full legal protection and participation in government." },
  { id: "residence", name: "Residence", summary: "Protected residents.", description: "Protected residents without full political standing." },
  { id: "limitedRights", name: "Limited Rights", summary: "Restricted civic access.", description: "Basic protections with limited civic participation." },
  { id: "nonCitizen", name: "Non-Citizen", summary: "No civic standing.", description: "No formal citizenship status under current law." },
];

export const MIGRATION_OPTIONS: Array<SpeciesRightsOption<MigrationRightsId>> = [
  { id: "free", name: "Free Migration", summary: "Best happiness and growth.", description: "Species can freely seek opportunity inside the empire." },
  { id: "controlled", name: "Controlled Migration", summary: "Managed movement.", description: "Migration is permitted through state-controlled channels." },
  { id: "prohibited", name: "Migration Prohibited", summary: "Lower happiness and growth.", description: "Species cannot legally relocate without special authorization." },
];

export const WORK_ELIGIBILITY_OPTIONS: Array<SpeciesRightsOption<WorkEligibilityId>> = [
  { id: "allJobs", name: "All Jobs", summary: "No job restrictions.", description: "Species may work in every available job class." },
  { id: "noAuthority", name: "No Authority Jobs", summary: "No upper-class authority jobs.", description: "Species cannot fill administrator or equivalent authority jobs." },
  { id: "laborOnly", name: "Labor Only", summary: "Lower-class jobs only.", description: "Species can only fill lower-class labor and service jobs." },
];

export const DEFAULT_SPECIES_RIGHTS: SpeciesRights = {
  livingStandard: "basic",
  citizenship: "fullCitizenship",
  migration: "controlled",
  workEligibility: "allJobs",
};

const DETERMINISTIC_PRESETS: SpeciesSetup[] = [
  { speciesName: "Humans", archetypeId: "humanoid", traitIds: ["adaptive"] },
  { speciesName: "Aurelians", archetypeId: "avian", traitIds: ["intelligent", "delicate"] },
  { speciesName: "Varkon", archetypeId: "reptilian", traitIds: ["resilient", "slowBreeders"] },
  { speciesName: "Pelagics", archetypeId: "aquatic", traitIds: ["agrarian", "communal"] },
  { speciesName: "Mycelians", archetypeId: "fungoid", traitIds: ["conservationist", "unruly"] },
];

export function isSpeciesArchetypeId(value: unknown): value is SpeciesArchetypeId {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(SPECIES_ARCHETYPE_BY_ID, value);
}

export function isSpeciesTraitId(value: unknown): value is SpeciesTraitId {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(SPECIES_TRAIT_BY_ID, value);
}

export function sanitizeSpeciesName(value: unknown, fallback = "Founders"): string {
  const text = typeof value === "string" ? value.trim() : "";
  if (!text) return fallback;
  return text.slice(0, 48);
}

export function validateSpeciesTraits(traitIds: readonly unknown[]): SpeciesTraitValidation {
  const normalizedTraitIds: SpeciesTraitId[] = [];
  const errors: string[] = [];
  const seen = new Set<SpeciesTraitId>();
  for (const raw of traitIds) {
    if (!isSpeciesTraitId(raw)) {
      errors.push("Unknown species trait.");
      continue;
    }
    if (seen.has(raw)) {
      errors.push("Duplicate species traits are not allowed.");
      continue;
    }
    seen.add(raw);
    normalizedTraitIds.push(raw);
  }
  if (normalizedTraitIds.length > SPECIES_TRAIT_MAX_COUNT) {
    errors.push(`Species can have at most ${SPECIES_TRAIT_MAX_COUNT} traits.`);
  }
  const spent = normalizedTraitIds.reduce((sum, traitId) => sum + SPECIES_TRAIT_BY_ID[traitId].pointCost, 0);
  const remainingPoints = SPECIES_TRAIT_POINT_BUDGET - spent;
  if (remainingPoints < 0) {
    errors.push("Species trait point budget exceeded.");
  }
  return {
    valid: errors.length === 0,
    remainingPoints,
    errors,
    normalizedTraitIds,
  };
}

export function normalizeSpeciesSetup(raw: unknown, fallbackName = "Founders"): SpeciesSetup {
  const record = raw && typeof raw === "object" ? raw as Partial<SpeciesSetup> : {};
  const archetypeId = isSpeciesArchetypeId(record.archetypeId) ? record.archetypeId : "humanoid";
  const validation = validateSpeciesTraits(Array.isArray(record.traitIds) ? record.traitIds : []);
  return {
    speciesName: sanitizeSpeciesName(record.speciesName, fallbackName),
    archetypeId,
    traitIds: validation.valid ? validation.normalizedTraitIds : [],
  };
}

export function createDefaultSpeciesForFaction(factionId: number, factionName: string): SpeciesState {
  const preset = DETERMINISTIC_PRESETS[Math.abs(factionId) % DETERMINISTIC_PRESETS.length];
  const setup = normalizeSpeciesSetup(preset, factionName);
  return {
    id: `species-faction-${factionId}`,
    name: setup.speciesName,
    archetypeId: setup.archetypeId,
    traitIds: setup.traitIds,
    originFactionId: factionId,
  };
}

export function createSpeciesFromSetup(factionId: number, setup: SpeciesSetup): SpeciesState {
  const normalized = normalizeSpeciesSetup(setup, `Species ${factionId + 1}`);
  return {
    id: `species-faction-${factionId}`,
    name: normalized.speciesName,
    archetypeId: normalized.archetypeId,
    traitIds: normalized.traitIds,
    originFactionId: factionId,
  };
}

export function normalizeSpeciesState(raw: Partial<SpeciesState> | undefined, fallback: SpeciesState): SpeciesState {
  const archetypeId = isSpeciesArchetypeId(raw?.archetypeId) ? raw.archetypeId : fallback.archetypeId;
  const validation = validateSpeciesTraits(Array.isArray(raw?.traitIds) ? raw.traitIds : fallback.traitIds);
  return {
    id: typeof raw?.id === "string" && raw.id.trim() ? raw.id.trim() : fallback.id,
    name: sanitizeSpeciesName(raw?.name, fallback.name),
    archetypeId,
    traitIds: validation.valid ? validation.normalizedTraitIds : fallback.traitIds,
    originFactionId: Number.isInteger(raw?.originFactionId) ? Number(raw?.originFactionId) : fallback.originFactionId ?? null,
  };
}

function normalizeRightsOption<T extends string>(value: unknown, options: Array<SpeciesRightsOption<T>>, fallback: T): T {
  return options.some((option) => option.id === value) ? value as T : fallback;
}

export function normalizeSpeciesRights(raw: Partial<SpeciesRights> | undefined): SpeciesRights {
  return {
    livingStandard: normalizeRightsOption(raw?.livingStandard, LIVING_STANDARD_OPTIONS, DEFAULT_SPECIES_RIGHTS.livingStandard),
    citizenship: normalizeRightsOption(raw?.citizenship, CITIZENSHIP_OPTIONS, DEFAULT_SPECIES_RIGHTS.citizenship),
    migration: normalizeRightsOption(raw?.migration, MIGRATION_OPTIONS, DEFAULT_SPECIES_RIGHTS.migration),
    workEligibility: normalizeRightsOption(raw?.workEligibility, WORK_ELIGIBILITY_OPTIONS, DEFAULT_SPECIES_RIGHTS.workEligibility),
  };
}

export function createDefaultSpeciesRightsState(factionId: number, speciesIds: readonly SpeciesId[] = []): FactionSpeciesRightsState {
  return {
    factionId,
    rightsBySpeciesId: Object.fromEntries(speciesIds.map((speciesId) => [speciesId, { ...DEFAULT_SPECIES_RIGHTS }])),
  };
}

function allowedIdsForSpeciesPolicy(category: SpeciesRightsCategory, optionId: string, speciesPolicy = "managedResidency"): boolean {
  if (speciesPolicy === "pluralistProtections") {
    if (category === "livingStandard") return ["luxurious", "comfortable", "basic"].includes(optionId);
    if (category === "citizenship") return ["fullCitizenship", "residence"].includes(optionId);
    if (category === "migration") return ["free", "controlled"].includes(optionId);
    if (category === "workEligibility") return ["allJobs", "noAuthority"].includes(optionId);
  }
  if (speciesPolicy === "stratifiedSpeciesCodes") return true;
  if (category === "livingStandard") return ["comfortable", "basic", "subsistence"].includes(optionId);
  if (category === "citizenship") return ["fullCitizenship", "residence", "limitedRights"].includes(optionId);
  if (category === "migration") return ["free", "controlled", "prohibited"].includes(optionId);
  if (category === "workEligibility") return ["allJobs", "noAuthority"].includes(optionId);
  return true;
}

function allowedByCivilRights(category: SpeciesRightsCategory, optionId: string, civilRights = "civicRegistry"): boolean {
  if (civilRights === "martialRestrictions") return true;
  if (civilRights === "universalFranchise") {
    if (category === "livingStandard" && optionId === "oppressed") return false;
    if (category === "citizenship" && optionId === "nonCitizen") return false;
    if (category === "workEligibility" && optionId === "laborOnly") return false;
  }
  if (category === "livingStandard" && optionId === "oppressed") return false;
  if (category === "workEligibility" && optionId === "laborOnly") return false;
  return true;
}

function optionReason(category: SpeciesRightsCategory, optionId: string, selections: SpeciesLawSelections): string | undefined {
  if (!allowedIdsForSpeciesPolicy(category, optionId, selections.speciesPolicy)) return "Blocked by Species Policy law.";
  if (!allowedByCivilRights(category, optionId, selections.civilRights)) return "Blocked by Civil Rights law.";
  return undefined;
}

function withAvailability<T extends string>(
  category: SpeciesRightsCategory,
  options: Array<SpeciesRightsOption<T>>,
  selections: SpeciesLawSelections,
): Array<SpeciesRightsOptionAvailability<T>> {
  return options.map((option) => {
    const reason = optionReason(category, option.id, selections);
    return { ...option, allowed: !reason, reason };
  });
}

export function getLegalSpeciesRightsOptions(selections: SpeciesLawSelections = {}): LegalSpeciesRightsOptions {
  return {
    livingStandards: withAvailability("livingStandard", LIVING_STANDARD_OPTIONS, selections),
    citizenship: withAvailability("citizenship", CITIZENSHIP_OPTIONS, selections),
    migration: withAvailability("migration", MIGRATION_OPTIONS, selections),
    workEligibility: withAvailability("workEligibility", WORK_ELIGIBILITY_OPTIONS, selections),
  };
}

function clampOption<T extends string>(
  current: T,
  options: Array<SpeciesRightsOptionAvailability<T>>,
  fallback: T,
): T {
  if (options.some((option) => option.id === current && option.allowed)) return current;
  if (options.some((option) => option.id === fallback && option.allowed)) return fallback;
  return options.find((option) => option.allowed)?.id ?? fallback;
}

export function normalizeSpeciesRightsForLaws(raw: Partial<SpeciesRights> | undefined, selections: SpeciesLawSelections = {}): SpeciesRights {
  const rights = normalizeSpeciesRights(raw);
  const legal = getLegalSpeciesRightsOptions(selections);
  return {
    livingStandard: clampOption(rights.livingStandard, legal.livingStandards, DEFAULT_SPECIES_RIGHTS.livingStandard),
    citizenship: clampOption(rights.citizenship, legal.citizenship, DEFAULT_SPECIES_RIGHTS.citizenship),
    migration: clampOption(rights.migration, legal.migration, DEFAULT_SPECIES_RIGHTS.migration),
    workEligibility: clampOption(rights.workEligibility, legal.workEligibility, DEFAULT_SPECIES_RIGHTS.workEligibility),
  };
}

export function getSpeciesEconomyEffects(species: SpeciesState | undefined, rights: SpeciesRights = DEFAULT_SPECIES_RIGHTS): SpeciesEconomyEffects {
  const effects: SpeciesEconomyEffects = {
    habitabilityAdd: 0,
    growthMultiplier: 1,
    housingUsageMultiplier: 1,
    amenitiesMultiplier: 1,
    goodsUpkeepMultiplier: 1,
    happinessAdd: 0,
    crimeAdd: 0,
    stabilityAdd: 0,
  };
  for (const traitId of species?.traitIds ?? []) {
    if (traitId === "adaptive") effects.habitabilityAdd += 10;
    if (traitId === "nonadaptive") effects.habitabilityAdd -= 10;
    if (traitId === "rapidBreeders") effects.growthMultiplier *= 1.1;
    if (traitId === "slowBreeders") effects.growthMultiplier *= 0.9;
    if (traitId === "communal") effects.housingUsageMultiplier *= 0.9;
    if (traitId === "charismatic") effects.amenitiesMultiplier *= 1.1;
    if (traitId === "conservationist") effects.goodsUpkeepMultiplier *= 0.9;
    if (traitId === "wasteful") effects.goodsUpkeepMultiplier *= 1.15;
    if (traitId === "resilient") {
      effects.crimeAdd -= 5;
      effects.stabilityAdd += 1;
    }
    if (traitId === "unruly") effects.crimeAdd += 5;
  }

  if (rights.livingStandard === "luxurious") {
    effects.goodsUpkeepMultiplier *= 1.85;
    effects.happinessAdd += 12;
    effects.crimeAdd -= 6;
    effects.growthMultiplier *= 1.05;
  } else if (rights.livingStandard === "comfortable") {
    effects.goodsUpkeepMultiplier *= 1.25;
    effects.happinessAdd += 5;
    effects.growthMultiplier *= 1.02;
  } else if (rights.livingStandard === "subsistence") {
    effects.goodsUpkeepMultiplier *= 0.75;
    effects.happinessAdd -= 8;
    effects.crimeAdd += 5;
    effects.growthMultiplier *= 0.95;
  } else if (rights.livingStandard === "oppressed") {
    effects.goodsUpkeepMultiplier *= 0.4;
    effects.happinessAdd -= 20;
    effects.crimeAdd += 14;
    effects.growthMultiplier *= 0.88;
  }

  if (rights.citizenship === "fullCitizenship") effects.happinessAdd += 4;
  if (rights.citizenship === "limitedRights") effects.happinessAdd -= 5;
  if (rights.citizenship === "nonCitizen") {
    effects.happinessAdd -= 12;
    effects.crimeAdd += 5;
  }

  if (rights.migration === "free") {
    effects.happinessAdd += 2;
    effects.growthMultiplier *= 1.03;
  } else if (rights.migration === "prohibited") {
    effects.happinessAdd -= 4;
    effects.growthMultiplier *= 0.96;
  }

  if (rights.workEligibility === "noAuthority") effects.happinessAdd -= 2;
  if (rights.workEligibility === "laborOnly") {
    effects.happinessAdd -= 8;
    effects.crimeAdd += 6;
  }
  return effects;
}

export function getSpeciesJobOutputMultiplier(species: SpeciesState | undefined, job: string, resource: string, jobClass: string): number {
  let multiplier = 1;
  for (const traitId of species?.traitIds ?? []) {
    if (traitId === "intelligent" && job === "researcher" && resource === "research") multiplier *= 1.1;
    if (traitId === "industrious" && job === "miner" && resource === "minerals") multiplier *= 1.1;
    if (traitId === "agrarian" && job === "farmer" && resource === "food") multiplier *= 1.1;
    if (traitId === "ingenious" && job === "technician" && resource === "energy") multiplier *= 1.1;
    if (traitId === "delicate" && jobClass === "lower") multiplier *= 0.95;
  }
  return multiplier;
}

export function canRightsWorkJob(rights: SpeciesRights, jobClass: string): boolean {
  if (rights.workEligibility === "allJobs") return true;
  if (rights.workEligibility === "noAuthority") return jobClass !== "upper";
  return jobClass === "lower";
}
